apiVersion: v1
kind: Service
metadata:
  name: healthcheck-appointments
spec:
  type: LoadBalancer
  selector:
    app: healthcheck-appointments
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
